#' Prepare Strava session
#'
#' This function is the equivalent of prepare_garmin_data for data generated by
#' generate_strava_session() using the Strava API.
#'
#' Type "?prepare_garmin_session" in the R console for more information.
#'
#'@param dataframe Tibble/dataframe
#'@param max_hr Maximum heart rate (BPM)
#'@param body_weight Body weight in kilograms
#'
#'@examples
#'
#'session <- prepare_garmin_session(session, max_hr = 200, body_weight = 80)
#'
#'@export

prepare_strava_data <- function(dataframe, max_hr = 200, bw = 80) {
  dataframe <- dataframe |>
    rename(
      heart_rate = heartrate,
      power = watts,
      elapsed_time_sec = time,
      speed = velocity_smooth,
      grade = grade_smooth,
      latitude = lat,
      longitude = lng
    ) |>
    mutate(
      hr_normalized = heart_rate / max_hr * 100,
      pwr_normalized = power / bw,
      elapsed_time_min = elapsed_time_sec / 60
    ) |>
    select(
      elapsed_time_sec, elapsed_time_min, heart_rate, hr_normalized,
      power, pwr_normalized, distance, cadence, speed, altitude, grade,
      latitude, longitude
    ) |>
    as_tibble()
}
